name: postalhub_admin_cms
description: "Postalhub CMS"

publish_to: 'none' 

version: 25.2.2302+7

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  animations: ^2.0.8
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  path: ^1.9.0
  firebase_core: ^2.31.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.5.5
  firebase_auth: ^4.20.0
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+4
  visibility_detector: ^0.2.0
  shimmer: ^2.0.0
  file_picker: ^8.0.3
  another_stepper: ^1.2.2
  image_picker_for_web: ^3.0.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.0
  barcode_scan2: ^4.3.3
  permission_handler: ^11.3.1
  image_picker_web: ^4.0.0
  firebase_messaging: ^14.9.4
  image_network: ^2.5.6
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  camera: ^0.11.0+2
  flutter_markdown: ^0.7.4+3
  flutter_image_compress: ^2.3.0
  firebase_app_check: ^0.2.2+7
  
  
  
  ##camera: ^0.11.0+2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/postalhub_logo.jpg
  - assets/gif/not_found.gif
  - assets/gif/search.gif

  fonts:
      - family: GoogleSans
        fonts:
          - asset: assets/fonts/google_sans_regular.ttf
          - asset: assets/fonts/google_sans_italic.ttf
            style: italic
      - family: Kaleko
        fonts:
          - asset: assets/fonts/kaleko_regular.ttf
